name: dapperFLAudio
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.11
  - pip
  # - cuda-cudart
  # - cuda-version=12
  - mpi4py
  - scikit-learn
  - numpy
  - h5py
  - setproctitle
  - networkx
  - tqdm
  - pip:
      - pyflakes
      - wandb
      - -r requirements.txt
